name: application validation

on:
    
    push:
        branches:
            - main
    
    pull_request:
        branches:
            - main
        types:
        - opened
        - reopened
        - synchronize

    workflow_dispatch:            

            

jobs:
    validate-application:
        runs-on: ubuntu-latest

        steps:
            
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                java-version: '21'
                distribution: 'temurin'

                
            - name: display file
              run: ls -la
            
            - name: Install Dependencies
              run: mvn clean install
            
            - name: Run Unit Tests
              run: mvn clean test   

            - name: Display workflow trigger
              run: 'echo "Workflow triggered by: ${{ github.event_name }}"'
  

            
