name : push_ci

on:
    workflow_dispatch

jobs:
    push:
        runs-on:
            ubuntu-latest
        
        steps:

            - name: print hi
              run : echo "Hello world"

        