name : push_ci

on:
    push:
        branches:
            - main

jobs:
    push:
        runs-on:
            ubuntu-latest
        
        steps:

            - name: print hi
              run : echo "Hello world"

        